
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app-container
    environment:
      db_url: jdbc:mysql://mysql:3306/my_database
      db_user: root
      db_password: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: